version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    restart: always
    ports:
      - 9090:9090
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=9090
    command: start-dev
    volumes:
      - ./data:/opt/keycloak/data/h2/
