version: "3.9"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.6-management
    #restart: unless-stopped
    hostname: rabbitmq
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      #- ./data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
