services:
  minio:
    image: minio/minio:latest
    ports:
      - "29000:9000"
      - "29001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    command: server /data --console-address ":9001"

  mc:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo Waiting 5 seconds...;
      sleep 5;
      mc alias set myminio http://minio:9000 admin adminadmin;
      mc mb myminio/goodbucket;
      echo 'Bucket created.';
      "
