version: '3'
services:
  minio:
    image: minio/minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    networks:
      - kafkanet

networks:
  kafkanet:
    external: true