version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: bahmanz
      POSTGRES_DB: defaultdb
    ports:
      - "5432:5432"
      
  pgadmin4:
    image: dpage/pgadmin4:6
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: 1
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "15432:80"

