version: '3'
services:
  redis:
    image: redis:7.0.4
    restart: always
    ports:
      - 6379:6379
  redisinsight:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - '8001:8001'
    volumes:
      - ./data:/db 
